#!/usr/bin/env ruby
require 'gss2csv'

session = Gss2csv::Auth.session
spreadsheet = Gss2csv::Spreadsheet.spreadsheet(session)
worksheet_name = 'apps'
target_worksheet = Gss2csv::Spreadsheet.worksheet_by_name(
  worksheet_name,
  spreadsheet
)

required_column_numbers = Gss2csv::Worksheet.required_column_numbers(target_worksheet)

headers = Gss2csv::Worksheet.headers(target_worksheet)
desired_hashes = Gss2csv::Worksheet.desired_hashes(target_worksheet, headers)

puts "required_column_numbers: #{required_column_numbers}"
puts "desired_hashes.count: #{desired_hashes.count}"
puts "desired_hashes[100]: #{desired_hashes[100]}"
